name: Keep Render Alive

on:
  schedule:
    # Runs every 12 minutes
    - cron: '*/12 * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render Web Service
        run: |
          curl -s "${{ secrets.RENDER_APP_URL }}" > /dev/null
